import { ThemeProvider } from "@/components/theme-provider"

export const metadata = {
  title: 'MysteryMessage',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >{children}</ThemeProvider></body>
    </html>
  )
}
